export const types = {
  LOGIN: {
    ACTION: 'LOGIN.ACTION',
  },
  REFRESH: {
    ACTION: 'REFRESH.ACTION',
    FAIL: 'REFRESH.FAIL',
  },
  LOGINFB: {
    ACTION: 'LOGINFB.ACTION',
  },
  LOGINGOOGLE: {
    ACTION: 'LOGINGOOGLE.ACTION',
  },
  LOGOUT: {
    ACTION: 'LOGOUT.ACTION',
  },
  RESET: {
    REQUEST: 'RESET.REQUEST',
    SUCCESS: 'RESET.SUCCESS',
    FAILURE: 'RESET.FAILURE',
  },
  SIGNUP: {
    ACTION: 'SIGNUP.ACTION',
  },
  USER: {
    REQUEST: 'USERNAME.REQUEST',
    RESPONSE: 'USERNAME.RESPONSE',
    ERROR: 'USERNAME.ERROR',
  },
}



