export const types = {
  LOGIN: {
    ACTION: 'LOGIN.ACTION',
    REQUEST: 'LOGIN.REQUEST',
    SUCCESS: 'LOGIN.SUCCESS',
    FAILURE: 'LOGIN.FAILURE',
  },
  LOGINFB: {
    REQUEST: 'LOGINFB.REQUEST',
    SUCCESS: 'LOGINFB.SUCCESS',
    FAILURE: 'LOGINFB.FAILURE',
  },
  LOGINGOOGLE: {
    REQUEST: 'LOGINGOOGLE.REQUEST',
    SUCCESS: 'LOGINGOOGLE.SUCCESS',
    FAILURE: 'LOGINGOOGLE.FAILURE',
  },
  LOGOUT: {
    REQUEST: 'LOGOUT.REQUEST',
    SUCCESS: 'LOGOUT.SUCCESS',
    FAILURE: 'LOGOUT.FAILURE',
  },
  RESET: {
    REQUEST: 'RESET.REQUEST',
    SUCCESS: 'RESET.SUCCESS',
    FAILURE: 'RESET.FAILURE',
  },
  SIGNUP: {
    REQUEST: 'SIGNUP.REQUEST',
    SUCCESS: 'SIGNUP.SUCCESS',
    FAILURE: 'SIGNUP.FAILURE',
  },
}



